[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "5d9a0a97b2743ae7df94c3160766ab12afc04fab"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "c9ff868c1668d83da0bced9cc1ac22af5163ab637c26991f806b0e933b19110c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "a764df776319d44cac5ac6c64807d27a683be4e4"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "14fe592941d04a5de5ecb60e6f1aeabd3de47fa857d56ec80246307d3a6e739a"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "6fcfa89f981d7b3e536a22f247b843daf9d7db2d"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "da98bd14485a459af5ec6fcf286622b670bd4d518e91b49a747b5540fb8496a9"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9132d678b0f07bebede5166395944a03b9557357"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "12b00f0d5396269e652f2be87958df100a526968508b2ccae76ae1780834449c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b4488efb0d884220a56d7b3adc085d23d8f3c3e"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "8897bb5af89105543116cd35c860a88698c6e93a0c2107dd6357778afc2debf1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1245e7c3fb027bd0536e3041ec56d8e560d4795"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "7bfbb06759cb858f3786fc6a7e5cd948cf12662a52afb3f2e6eaec64501da094"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36ab182fe8eabf0c7dedc51768ba6e942e6b5829"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "70afe83f486cc675b752edb8d3fda83fc330af3f84b7f881537f2e444fe351b2"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "f140052feed38c9276d308bb2b0e35688295efbf"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "657f005b4542a1eaf9120de57960554d505a613b581acb0b897886b23fa0ea96"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "fb0bc83549490934a5899cf5a5a9303368400b0b"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "9569d2ae21886308ed3d154d639bc574b48679d77e4ef4bfab40430d17c8aaa5"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "3ef55e09362fce16682107b3d0eb7cd327d5664f"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "72d41f97bdb273107308fb2f916fb6e52efa823e5377d99f355f0427ac6f2a3b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "039bec19426cb9940596494c553a6ac74d1ff603"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "1ebbf423f53def478e8712f54dfc0f6a3e6aabb915939d9f7f0007e96b047a24"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "6b202038124cc722b37aa1b08584c9dfde6d63cb"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "756700b0b685e941da8b044e4e714468ad342ae08ca9bcda7c3bded6961e44da"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "d90704e54bf4094a85939ed0d066ff3b271afc9e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ea03f79ab56a973217517313ebe04a0d87bc06c389ea92428ae9294bbcac5830"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "f5a27054b86b325c0509ecb7b8710b4252c6b4db"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "4de601455849e62f46f051bb632b323233188cbe34530c419df29667c3dc2836"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "da553a0ac27ea81b90f7a0e3ab53097748205a5e"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "abb4868f75398fd47c27db701019479c28e9be2935456f970e2fe9b08afab760"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "bf6a9502b3c30547e2bb9a7193e9a471862d0774"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "9131b08683076eef4c251a2c48669063f56d8b66f3eb5ced6b085c587112e454"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.1+0/LibSSH2.v1.10.1.x86_64-w64-mingw32.tar.gz"
