[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "c47f73b553875ba9e891bc997dd6cee3d6c36069"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "ef229dbd085a774ae2e83cd4d47f48c823ac77a8ffc9228ecd4616836bf71e74"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "06a8754923d590a8959f9bcbc04f279c306182e3"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "0311e47f3d92f1892af9d7c225ab44d4f79e0a5a8424f73b2d91b64ddd3a93ef"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "9c8ff64ff89337836e909d87c13ac3075715c8ea"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "d80134e53d83d1fb314c6b4c4312d87c3bfe77dd0c24f8a8c6c2e93f0671b775"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "801ad6c11f7614eb233d28aca80fe206cb461f0e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "14e38b4467e705cbe2924003b5f75df3396e3ce6be4be3346cd679fd3f49f4d3"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3ba3c12f2709ac16228f0c2b6b3c9bb01a1f1fc"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "dd94de82e2719143c36534e94da179f4dd991628990f5a63a90b6f6d77eeda3b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6184a0ec814522f95cf0e630a0f58f74986bba58"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "29ec227ebf6bdb7e7b3d4b076a756f86231db32b32750ba9bd02882b2c5021a7"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c692c8a3a458581ad390774b60e2475233c2fd5"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ad2178f45ad099ebcefaf205ca42a31365eb2d5a53163edde8a9e3153bbee7a9"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "1af19542850178f4e13de9770573cfd429b1a81c"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ace270747574db6dd4f39d03021998c5a43498dc81265d0df248f8c4bb0c7ee1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "538885d368c785c1d2431df93385cfd208a0ab1c"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "4b4a8145af0c9b044deac328952aecce0479aff31ca26740deb43dd1d445bc4d"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "cc12cb648046b3133793cacad6b678551b2d5f0d"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "84e7e1eb185271040a2803a321a1c3fcb7037045b7fef8fdbc1c620b75bd03b7"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "2926e73d3742b779ac98db0dee4bedbc4f534d8b"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "93f7bb1da499cae9a49916ae0934007537204f97c3a178aaf7ad8c2d89cc83d8"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "6e0227134e960dbb2f65151093d1097e0d385074"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "7c72eb2b9e99c5e5ff577f26e028f0fbd6c43b5fe1959afe22bc131333baa3ba"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "4ec6cb8c64b99df753dc3c8bd7f7c86d8f7e0af5"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "6f5cfa8574c96381c58c36244220f736ebd2f7ba31d368992e00b6a7b8e47560"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "86cb5b8b596cb33014a7ff99b82b83033bfbf726"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "0e5ac4d5f56d124e51e5eaa1de8dd6902256dfd2e9e4f64b31ba770ecb924f68"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "b3f41caab039ad43cc1e9ac5b3465d8ba3d34ce5"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "9f82c095b47243c769acadab6be3c5f22e7e04aa5afe4ce8d293a58a66c5049e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "064b7e92ffb9851b86781ed37f61cd1171001e24"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "a06005934d037315bd9b6cbff3c4ae2a25a70335922a7a020bf2e581c5351706"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+3/LibSSH2.v1.9.1.x86_64-w64-mingw32.tar.gz"
