[[LibSSH2]]
arch = "armv7l"
git-tree-sha1 = "f0ee7f38d6526ee8475e1b84c3ed07ca9e71e4bd"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "6691f6e5e8e095ba0c68dd3968c64356097398cd1984ead094a9cd6256953821"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.arm-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "26c7d3a6c17151277018b133ab0034e93ddc3d1e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ffe52a373dffe47ca39af12549830c6dd7dd2096472ee8a324a31cecea3ef5ee"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "31e8675b169e056bc92aacf093df6659fa0dbdcd"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "9b3bbc7a6ebb96c9a778681f167318c0b18c98544bebfb3c1db5f2ce9f118754"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "c0398510df5f6209473cd1cb0f7eabb7a18e8747"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "3acd7b0d7a088216fc9755b351e71de731506ad5b76d0c5861e053d797363368"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "84a8c00f29c1b850bdca5685ffe32267db3ec632"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "b071fc09136638a9e6bfd7e6dde663f77a45fbd4614671d86a4172928d6b2dfb"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.x86_64-apple-darwin14.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "ec57f1d9714753f2e415a4fbbbfd1a2b948cb264"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "204dd622934b247297f03b3f7bce6ef1e3e0ded03a763bba6e881090ff02f05e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "59b4161a44fa7b3cad572008a5e7bac17a888a19"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "9ebbae40b047d0e55d3b0d3a2bb448373453797dfcb739e0c3845cecee89a561"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.x86_64-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "d75c1968945b3fe047b73aecfe05db6a70355e5f"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "2450f45e82ee37ed95cb1838db58a59784c4147a001830525a4cb2d3f3261f7e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "0eac5def1e41e9ad3290aaa69142ff08c7fd7d3f"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "e83bad8c959e0a9516dfca90e87ebfcb00acb8fb68c6d6468e0241dab6f0dbe0"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "8b85968f9e6269e9b3a1a166e6bece215994cbc5"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "8a3c41b7bf58511b1989df7226cfd5d580e75dcfb5aab346135095b3e2e385a9"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "b7446864293dec860af007a036b61f42d8b697e2"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "87208caaa88030df82f4b8dbb993c0b95b625c1bf7a4ea38989528c64aec58fa"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "7dfff0f0340f6f2229e2c59a53c2a573c681a115"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "86030b7635ebd9c7debe3e7f2fb72b360b8607f6e4dce02e4c59548d283a38df"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "armv7l"
git-tree-sha1 = "70a1a0547242f639bfa1e8ddb1f2dc6460d3fff3"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "152d3a6aa8fe3b4093f6871f49f8ad91d35fe5985a674727b44ed05bb0c36b6e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+1/LibSSH2.v1.9.0.arm-linux-musleabihf.tar.gz"
