[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "f407e35016ae5b9bed495ad6ab74cc5783b1aa59"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "07994d08a774cdf133b54cae66baf08f22338bfaad509a61b729509ff7abdc2d"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "74ecc8d6d4d9e133cc668e455f33528ae5afbe85"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "e34ae2837e9fb40c88fbf72884d9e4dc0d7582f52dc3006ca29bcf2a6237995c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "31c0c89049f75fc2e0d6fe5592937de98cd8ce18"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "97422798b19ca724a96663cec73166b85f4d8c35ea70fc042cf4866ae54b0951"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80edee53583a30ea81bdd2927d86c762813df0c1"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "9e30e379a843168fc656f961f386581802668b13134c092bf752ab0e860f417b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a21c57be9e50dc04ed9832610c691277373b8a46"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "fa771f82269cb604f8bf5c9e7bd8249bb21053377f2c32af6fc6fb90cf334824"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b9c20434795ce585ccf4f572f745f7bc76889004"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "fb896350ae4fc5cbd3fc4f5688dfbdc69f4af4d9f0040e8de58be2550f7b705f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e73d4a76b6b641e35872265f287c6497b19c528"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "d77dd0488ca8b241d6f56829eed10b5711ebb1e1e44213c5d9aa65d0d209d2e5"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "0198dc85111c88992ad807b06bba72eedb7183d2"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "89bd0ac6b94c855a1f0d1d2729248e366d18a36bc80381f8c5347027a1891b0f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "15598ff277c092ea28559acde3ef7ce8cfb3cf6b"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "2f2be9246b910686a2eac4e13edc1d96d7dfa0eb6f0f446041a5a7af0f52c1eb"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "723274f5d40fa33640e76cde90925fd1bdd96167"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "c695b6d77e80569062ad2ee549b73f056513e8db7bf640967a54af76d7d7ae30"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "1bb0c01e3dcae5626a6ea562e487c87dafbcad39"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "3b50756c959347a0005863fa650e928fc7e1fa1ae3bb386aa62594fe802b3572"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "b5847b306d80dbcbfcdf803608638eba17f40aea"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "1c999d978ae4cb11cff9300ffd81f97990b84eaabca8c3ca4a026f2e86489a8f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "a427abdceccca3b73ed3f3e56ba238855ae8a367"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "7fee68e19789fc53b59fbdb8d046090a574616d0579517120d91ca31aa42f36a"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "6f91ff7404561a71407673824c46529f548861ae"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "2eadf4ab4be0c107a7690607a1313e3d17c1544e43136bf1a5b5728ee9d4d3f1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "aa723d9d98e7021a92832beffe1c18d183575223"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "018b037c61fa55915cc28299ea5d7bc6ced05df0e00f67883d515b991a352642"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "977cc861708af57debfc6d9106b336835044ed3d"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "cec054fb0490be7fab587bd2a6de16c227805150adaecfdb061a5b4a8c6f0547"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2+1/LibSSH2.v1.10.2.x86_64-w64-mingw32.tar.gz"
