[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "f3fc0f9606e5eef0c00781ca41ba43719be8d657"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "5347746c5979398d1d24cd66f4b1b3b093aa112c12b0a5c1b5e873f8d7e21b1a"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "e6c594d301a79599c3eda722f46be4ba3b1a596a"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "fd7b4cfb0c6b9dbd96d2799291d0b01e9fc15701d5f9b92bff50470367148263"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "563205dd764bd267d16bc4d453cd62560c4e5c66"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "f556072892ab941d19c60e0edd64c87c8ed6b55e12b08378d1cb501ae1438413"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e38bde62de52534b6ed05a8d3a039744f9e52df3"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "21bd9c01efef2b62f36868608d8f2cabbe628c160070744f6847baf4854c2418"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9912680d39c6ddf61421a77d047266845d031dce"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "e2ba66ac4a6d2908df2599c2570f1f47fbff7e94163c7b346f51133dccc07ed6"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0bdf9bf659b412330a5bfb28cdb3b30c32dc754b"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "2c8b589dad809b4c3ba392e228a6f57cb51768c9e5a1fe2ed726a7399dbec004"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa59931f0958450352f6dc0b527fd3fa7e65ed31"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "13e07861af959a7ad0f80fe1756181f524d94da86fef1e936e421c68ab2c5b53"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "1b6030249a0dd9ebdb7808ee0d5ce3b9c381b053"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "f93540ec59ca83de70d95a3faf05ba4aeac6e2847cae7e9966d6414d458b2e4c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "783047d4e0a7b6e543044306f018ee69de23fa86"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "180aa796750a2f69317a3eab815f3ac3d4d4e37901d409e891c64719d69784f5"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "f8b5eb74932380aa0990aab873c5cf6f485bcf50"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "d8cf398eb3b54eb6c778d81f557bf68b850805d9608eed696e8dbaa13df2140c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "a4521009723b00a21084b7b48087567dba6f9aad"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "7e929d0e41fb88857440ea396fde8c7967785c274ce4074e849f9c09d7a18cc2"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "a85a0f3592cf3ac179ef352d84ec8902de190545"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "3d2ef80074eb959b0bb23b6ecdc00f2405f170daf036458fbd7a654f4b92b194"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "e1f0c788e4b359d2b3b55d9ca65c983d0b445054"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "1ee9eaa41e11429585ad2d7ddd787dee58d55c7d9f47e17bc53e4bafba2248b2"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "852a8cd62a6828447518f99a3ebed869d75abde1"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibSSH2.download]]
    sha256 = "54fda29ba3d616d2eea0d299fe5e87b0270416a5f027d7f7cc069dd2a2335e9b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "32873a7152bd13b06e1d408a9a4b892f213c5412"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "693937c1589a44491aa98a45aedf140fbd5737ad95cf55aa70e2c8b4fd75c3bd"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "632c124b9fc3fa286151a4496a8fcdcc88d074a0"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "9999bf3254bfa54e972516218e594cc18a61a196b8e0c9dd7b8686e0022db806"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "4683af5f9df352085a3ff43a9768704d33f118a1"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "778060b6886050d3161639249c9cb19acef914161d83a153579f56f8e28ed392"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+2/LibSSH2.v1.11.0.x86_64-w64-mingw32.tar.gz"
