[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "9a4ba8f12ce5bc82196afcd5667869fc56e312b2"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "4af614726058468b93b103b08cbf2468a0e8b8a91fc9dbe6e8d9daf1ab0757de"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "1b6d2554a5fdedbf217418d28b658451faf1178e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "1dfb2058192b0d1d12360dc103ce4d3362de8110decbc65f725794b72d95e0c3"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "bbf4c84aa7f1f5675e18fc8de97520de90dfc804"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "e4dc269dd55550d9b990aa88c4dec96c7f89272192f49becba520ed393b54624"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "c1fa96ff9d3a5738fa3d00416765712c58d690b5"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "582a57caf0203c433d1c9c5b49f5a6fb32c48c44c5b855ce17268da984209f3c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.aarch64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "da473553098b2f863922a74be354cb7f6aa8f0cc"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "03ef149a47c539a55bfe0ac60e93b7fe8c31b32a2c863ad3ccd9450739615e70"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b27ca745a00f0c7ace6b8e1df766f3fdb8a3bde"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ac575d8680a6e841e7bd76fcf9751fd19e0ddef5a8121fd6109b4f2a7f441157"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41de5c9cd6dd15322bf314765f663591c654701e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "bd0a13912178ac3e02b205861b4092fc3239a20846bbb382588bd4d316b157d3"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6fd6ea7f30f069145591d9e9dcab3f9483e9a597"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "5d9d4702aa46cc897454ac62a1e86eaa9b94457e88087bd00257e95408cb8781"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "a641d42db3263f67663dbf09e18bc14d658f095e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "711b802ed8ff3e020d7235271a996cda2b291ba308d7c1289d605578750cf205"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "db9fe7c146d148946ed3c149612cd920c20dcf7d"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "b74c5dc6952d69e2c30bb9f9c2deadd0c5c50b7f1e46178efabbb091035c8531"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "f5044b719c09cef6006fdf0601c1c8eda8e7a424"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "5576a90b384767eec07d080c2a846e882f2755d8ef59cf00c9cc77cda430c9b2"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "82235f8ae272ed89a890acf362a065c0d3d4e66d"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "8fe928720f88960ab5775b8bf396711df54e1dbb5eef139abe1320e5fa8a5611"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "riscv64"
git-tree-sha1 = "ae0a492d753e8b5e34055333c08e4a4f3c3c4e24"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "d62f818562703a00afaba49e51a507c6891fb725b8e99c953f51950501c4b7d1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.riscv64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "168e1d354aa1a4cee144a4b26244f7a70637a142"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "7971dbf3bc7ff73f82f03498643f8e7a7e1cdec8743c2da1c7f798ffb4bf069d"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "cd956de4af845c5a874162974dee1b093dbef27c"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "c894b587bdd57dd48aa9fe9a7d5672561bb7fb1f38bb4f070807b7401cd060b6"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "58df025f5d65fbd18adc22af1f961980bcd96e7a"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibSSH2.download]]
    sha256 = "613da340796e8f5e4054571baa4bf137a349100b25591ac71b3af74c6be5b71e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "4bdf9068b6044b28e0a977fa96c251fa6bf50e18"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "74cdebc0f1134e70a6fa93694605bbcc3e13181c16b254d27a08624c6e7fff09"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "5dae02623e4dd9ef5933cdbbc06bc37d21edc77e"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "31a6e5333f3bdbec64ab3969e7de00979411a269fcfbc5f352f3b651f0bb889e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "0013ab5a8b6bb5e6a2af065ed7b745a98770106e"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "4c40ff4e97dc78e02687c377c0024c4b27c418b8b83a396a8f32954c469a9a51"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+4/LibSSH2.v1.9.1.x86_64-w64-mingw32.tar.gz"
