[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "03fc28a7cac76345601b9a06346d39831878c4ee"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "937e7ae5bf605c4e08c978d8279990d23411e8d8badcee67945ec71980794f77"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "0948308734a0227510a36306f1097aef383daf52"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "df2de9675251a4ea7c10d3fed87333d5650a86fd493e03cfbec20b03258f636f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "d93c68f408952346f86a5b6c51bf686e31424d5a"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "388eca22859619b068b06f02a4d89e2d8d6920a42a35548a28ca8a7fc8bc3b1e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dad27a1da040f542bb0d03772107df6aa1739640"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "81b8f8425cd1025eb30d9f08147186fac609025e9768121e9128ddb504d1e9d9"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4fc214a73e819a732ac0565e3a690ddf9cc72f8d"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "85413a344eee161984403964e2aa7a17c40a9c417492e02956279209587d399c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc90b649f4911f6d012630c7d199b066b183b65e"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "67f09ff8eb50f7d9bf85c344ee6bbfb4ab9932ed052123bea38d636ac9d27510"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87cb72d6c1c5a55659604540d959a2812570ed1e"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "a3032b9f51c8e8ca146e61f601ae88201365a9364b6e618e3458c9bbe7fcfd1f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "49d7c79da1873515149e36de401c2b4fd38219e9"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "90282284ad22ef2b97c20e32cdc8265daac059f074d673fef581c549b16d08fc"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "558e40de5c70dbc442a949fa9f50db53adf3fbf5"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "8b9c5d9ac9fceaddd8d86424e19415cd3c0f016ae65383e05e65fc408544065b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "977f3fe6174b80432e691d9e611f220d0865cbd8"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "c599cdf521dccaf340893dcad8813e5339bfdaf362503bb97c2ff729eec16d75"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "3c8d6fad88bd5690d1ed83a6e25f1c8f4209eb57"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "33401b41cc86dded4ffe163b6d67684b17aa52e1c7878ab718eafcf5d37ebf37"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "a90b33da422530147f1e6645ac3cc9734ed074e9"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "214b8639e74053e62fe8e2e0f31ab73efad2ced2278bf9fa25e659fb7f59d7f0"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "d3e832bab8734ea6989a656a894bb8405483b599"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "db7c893819a42544446a24d27a2bb078f0d8065818c50e1d26291f076fc655c0"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "42a4a8edb09bf64310f2e251f64e95475b992fcf"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "55663a5c0d8ee66e314ad0ff61842cf8e809e629db198227c0c98b4154b6620b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "18bc4a4e126e8040b480eb961fa4a0d351090fa6"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "8ead54bce784857d02377ac1fbe571afffcd0051989f3b134271627838d6cb03"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "0548640b03c9c895c19470a8049db81fcde32f0e"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "a973c0d4d5d7f119b95ea309dd87ed76880d8085456457789ec6bc65c8d47ef9"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.1+1/LibSSH2.v1.9.1.x86_64-w64-mingw32.tar.gz"
