[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "a2d4950dd8acc0a28c2fe2aec89ba210a7439e65"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "9778ad4e8e8f2af5000cc64ce95aad5b43ad5b0a6d1046549590024f0553443d"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "60cf0a256f49ff1993c35f782c1e4f79c73440e8"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "8524f1a6fb2ef82e06ca818a4f89c2d6e4b9e3fcb35fff84b939dd205d1380ca"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "d3bbf98c43e111bac82d618d47a31c1bfca281aa"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "46ad2960e9acfc3a19f868864b992b02505320124340fc171dc8305c38722610"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "2e6127d678aedb7223542206a41c4603202d5fa9"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "958670ea12acdbf134896ee60a150281ad2f57819f3eb824b9b9baa4b7441feb"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.aarch64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccc2ebd67ad7cd6b7a065a63ac3662d92888651c"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "975fa2aac1d04bee16696d1d0c2d37234d3e6fd10460b2cfba3fe2e53297ce7e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35eb65eca0f6acf87ec2a0765f239c949bc9d76f"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "1a720696053015556d190bfd5a462c58ed95e63f93451a2c51e28ccd0a2f26d7"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d45aa1fee727397f9de36abd9815bf06f16772c"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "e40f91a42f0160ef032f06a3aa7dc5454260953afeb6076335a8b3f1d5ba0e61"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6c2dbdd74597874e6c8a4d4067c4a78b76a25f4"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ebe4c44a0bcd21ca2787cf4eb5c1040faee814aa8be280413c552bacacc60f1a"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "8cef71bc05b0a5608802277a5db900f5bef49e33"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "613d8aa464d347dadbf850c98088c07e2c5922d8259185d714d2e264a82d02c1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "2849ba32a42fd94119f671fe08f7385a65fdc00b"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "c8d6524b08bed1b5064ffb92f5df76c48fed1a23f9697c56d9eaf57bc3c28dd3"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "d69d3be506c861d715d0650fa92f6b3bb31b5e93"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "cb37c36e45a258b5e1b1d631236489ccd272fc3b25d04656ef0b120336c2a872"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "e9ee23836c9907dfcfcdc027b3f01c636c978413"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "d884333ff8d10338e82f4baba26d384e90f9cfa97105d6bf4c0d5d99dbd7cadf"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "riscv64"
git-tree-sha1 = "35c38ab02d2b73f3a3948ad0e4579db89766b1ef"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "aa5a65f4d78f612845d8ba5c0ad033f49851dc78dfc524e3c55657335552cfc1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.riscv64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "fc6b797acb73da9ebbd62bdd890f3ee32f50edcf"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "d6b4a2eebbd4edefa27a065b8fe0b8cf1c4cfe2ae26407d389ffaecafaa417fd"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "ddcdae9ee2f6a298c540b9ab72dae30b333d6493"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "3004335792972462c74c5658406fa7ed72c2c1e1c822b21a8f8668c61925b2d1"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "0accb65649823a9806ed94d1631b5f441cd0fe55"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibSSH2.download]]
    sha256 = "d9d0ccbf6e4cd15d630d0329ca7165809eafc0094a6c662e650672e7971541c5"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "dd13ba266567f291dac1e0f0258ecc64b46f8511"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "b06f43b5b29cd715f803d5e46ae9a3dc2b3dcb6c50a520bae93f4a3467854aa7"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "99141edc1a909166e5bb32c14841963755546807"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "5c23d6edcf2a4263768a06506f3ae1a7faf3ee4a5dc833e92dadd79b5bf7d11e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "941376d22dce7367742911ebfe8a3754a86008ae"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "d5c017d11f46de876c7bbdab0d388265bd4e10a5aabcec5826aabc0c4162ea97"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.102+0/LibSSH2.v1.11.102.x86_64-w64-mingw32.tar.gz"
