[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "a89f93022e0bb6bcbf555f46dac5f67431018add"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "155c956bcaf3dbb199db4c68eba4f8ca7b9d5021d8401c519f7f6f3c14730a07"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "e65d167eb3c9e77b83ee3c5ee04e01bc3081e477"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "4ff443277bae7f287d1167a48d7e8d5dd8f47c015124a45b78a2ee0538de8f5b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "a23585c02c13bd68a584364b2d54d81b80e5dbf9"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "545a9aef4884818cbcc6fe3b9feca29ca4cc8ad4f2a8c608ccfebed8e5f26e68"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "38a8e3cc4f309c81e2559175f0436fbeaa927029"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "0603f40945a4eda5de3802d8c0053c2f09a93d3221a4c8afa056579c997203c7"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.aarch64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a672e3c23f0475d81f13b96d82a8cfb9b9c5fc25"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "4ff4cac79aa94da095cbffde1b553a666c6073cf56da276a2bac93c54c2450a0"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf88e7d347bc9a7fac51e355fbe8077b76ff2bb7"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "ebb23f89466f6317d8f5484d30d95c4c63cd6b2cae421ad516840e4efe8ff126"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fba43257c28905225a47494ce05d11ee6a92b9a5"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "6d527df7f696d493072a3c9bae65da7037654e9f0ae09a00b8bafd3d7ede3a4a"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ec9cd57fa70e67338b8f8dd5f37896a901698ea"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "6f2eca1cb175ab86dd9db7017c544494841f8683424ee87d1472a9242ea9bb49"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "6025003f65738d94f1045597b7ee3284d0cf3627"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "f599faba1bf86e60b91de5f6d15a031922a98ec7adf6424834a99c2a7ffb25b3"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "dbcb2ea4f9f2126fbe49d32c2b0bf6524fc147b6"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "9b2a6cfa57aba3739cae8a576ba6a11a2ec57599f5d448b93b540f651046503f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "84ac46f2a5fce7cfdf7719b77bc363d458d88877"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "41166dc8b648430826f758ef8c85d28f035a885eea7e5151bb7ab97172e6439f"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "e70d56141124984505620cb0360945ef0b31fd70"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "b7a96d95e8e9f007db6069370276037ce6fe7f16d922aa0c5f2d4a82b1588b4b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "riscv64"
git-tree-sha1 = "94dfb48e86c03504f19f3e85aa4518d09d0fee10"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "9a655c62fc0f258c9777fdf11703ca293acb68f8ea639f9b11da0c177e46db48"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.riscv64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "bd62df1826bfa488255e29220f1709a95bd6010c"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "84f518a6820bcf0611aeec10b22a77eab5e9f75b74caa21141696c6fd36d5cca"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "77f8bb577176f937075c14b17655a35685c91636"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "875d483e1efcaa371b1c8d8612fcc0135cf6bfbeed9d7d42198fe9753726db74"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "c7dbebc0f8ea0fb4324bc855b7f15e7cb3a37b56"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibSSH2.download]]
    sha256 = "d6537328b05ae47b3dc6d690b0994f8a0c9816202b89e6ab762999991a11ca97"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "ad48f47ef6a8ac078c8bfe020087d1721d4c498f"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "7998437b0eb6ee6e3a6e5c596eac6794039aba344caa2d690ce9f63888c5fab3"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "890d48726fbcd7d6cd2d063750b2db05127af257"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "17caf4fc5123a999d65f746408c5a077a18ab301d552003a01ac3660d2d5b827"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "4915d5393918d27de6831d281b0fc0bd98f09667"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "8c17b42a30bd64aaabc4f7acb3f5d4e1fff1ca8de1857bc92b888d09dec06061"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.101+0/LibSSH2.v1.11.101.x86_64-w64-mingw32.tar.gz"
