[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "e0e61df90c18bbf9739b71ad66026e4fca2936cb"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "30a235677434347566acd0b9470e1d4ec6397be97f988b606c659bce5278d582"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.aarch64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "d41cd1135072244a69ad738337aff39bb8ba5394"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "f24b75f151dc134e85db801fc1abb79b1c73398b7b88b2e373717f9a06370f53"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "46db959ca9d9822dd541feca4037e569cdb13eb5"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "84a6e794effd4a7ba1b88ffb38d88fe915773a19f3bcb3d5066153fd4dea9084"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7f6eb2c80ee067555177d6472fb274869e98621"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "f44b723d69d8e8f89e6552ce4d71a65fefdb4fb134a7a23f01b0ffd0cb5f88ec"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.armv6l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a353ea8edd8300ef3959e132f3103f3a669a259a"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "cb88566137d5b990231a2d535636b7564131deeaf32a1848d3d9aae6b84d1588"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.armv6l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "450847832f82f5831dcad39920bdc129185acfc4"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "252fa78bb856c10b50d738ef147ed66ff6afed798a7792c3e5fb6b154789d89b"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a3afd988341d9744ef50b5189e9cff4629cb725"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "085115ff2f6dd98282779c9d6904c0bcacd51ec21c1bdf684d28b7522c0333b4"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "42e10214d775cf9eb0df467f79c3dc8947f358f9"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "45adf92bee53cea70e86d4d5d92bfaf4d82eaa2082f3c304a9348d68da9445c5"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "ff3b3148b3d9089319a2b233f1e3e777c19c5706"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "28218a31627c4cc37952aa0dedca4113273f666465e89c446a9834fcad794dec"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "e2611144c8c4cc319fc7bdd275131b659a7a30fa"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "52fe376598a1cfc94f71f243ec6599f7c7ab3ae88d89fead7278e6a77d61979c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "1690cc5d2b33c89cfc30ede94fd9a5731084ed44"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "b968ec14e8812edd590a429d0ae974ea85c21eecdf1317d31fcf7f0502103439"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "a2b328ec4ca67dff1ff0efa493c6f39332d88bac"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "f515dfe532943769d128bd85d03e76f2fa10ce9ade6fb04aead6967d66eaa516"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.x86_64-apple-darwin.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "cf526ed058f96d219eb35b06cf85a98903977b69"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "a9dc9a24b923f82c47f28d78952d4f7498f25900cd346688bb6229290bd65725"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "e3670c84655a6b3152f99ee0895fe19692ea7a55"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibSSH2.download]]
    sha256 = "259ca507f1b029ef049a7635b9a7f7aea17508ca7ebb5a0b29b6ea361c95bc80"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "05f80f425e1c8cf014cb08213b28f53e6803cb18"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "82b7090954e4b65af83b652fe89a64da2cdc45567e81cc4b62420d1d4f9eaab8"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "69f76d4bc208443a5f8dcb28cd509edb8612e649"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "099b39e811723180f4d643bd644fdcbda43b32b80db48c3face271fdba72e443"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.x86_64-unknown-freebsd.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "40736fbe27ade0c837ab4d92e546234bf94598c7"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "168109345ad23a58b5ea6d8c553dd217b28ff699bc8bad033c299a9717b200cb"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.11.0+5/LibSSH2.v1.11.0.x86_64-w64-mingw32.tar.gz"
